- hosts: windows
  vars:
    ansible_connection: winrm
    ansible_user: azureuser
    ansible_password: 4&EQdMWDiRn@cvc#O8pr
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: https
    ansible_winrm_operation_timeout_sec: 120
    ansible_winrm_read_timeout_sec: 140

  tasks:
    - name: Ensure connection works
      win_ping:
